// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjZThNsl2oalyABVvZ0KlO0qTGgduJh-Q',
    appId: '1:781181938019:web:4e89ba7be35c22dee80b56',
    messagingSenderId: '781181938019',
    projectId: 'lafapp-eec71',
    authDomain: 'lafapp-eec71.firebaseapp.com',
    storageBucket: 'lafapp-eec71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzG9f013lYCLTq06e1cLe90WWaB2CN_iI',
    appId: '1:781181938019:android:c33965effce532d9e80b56',
    messagingSenderId: '781181938019',
    projectId: 'lafapp-eec71',
    storageBucket: 'lafapp-eec71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOSALf-oMhyj2GuNV-4-9jLW6OxqWY4SI',
    appId: '1:781181938019:ios:c1cef8d74f6c74f9e80b56',
    messagingSenderId: '781181938019',
    projectId: 'lafapp-eec71',
    storageBucket: 'lafapp-eec71.firebasestorage.app',
    iosBundleId: 'com.example.laf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOSALf-oMhyj2GuNV-4-9jLW6OxqWY4SI',
    appId: '1:781181938019:ios:c1cef8d74f6c74f9e80b56',
    messagingSenderId: '781181938019',
    projectId: 'lafapp-eec71',
    storageBucket: 'lafapp-eec71.firebasestorage.app',
    iosBundleId: 'com.example.laf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjZThNsl2oalyABVvZ0KlO0qTGgduJh-Q',
    appId: '1:781181938019:web:b33edc4382199ad8e80b56',
    messagingSenderId: '781181938019',
    projectId: 'lafapp-eec71',
    authDomain: 'lafapp-eec71.firebaseapp.com',
    storageBucket: 'lafapp-eec71.firebasestorage.app',
  );
}
